markdown:      kramdown
description: Spice program is a company-sponsored open source and social impact program. Our goal is to make Futurice a better company and the world a better place.
baseurl: ""
sass:
     style: compressed
gems:
  - jekyll-sitemap
